# Generated by Django 4.1.7 on 2023-09-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audios',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='status',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='super_visor',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='user_name',
        ),
    ]
