# Generated by Django 4.1.7 on 2023-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_audios_admin_remove_audios_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='audio_file',
            field=models.FileField(upload_to='', verbose_name='Аудио файл'),
        ),
    ]
