"""
Django settings for two_level_morphanalyzer project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^=qgg&=clh4%^*(mxn!ap8jz#68r&@2e=i)cj+6-@8=(8=w^6t'


# Включите HTTPS, установив SECURE_PROXY_SSL_HEADER
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Укажите пути к сертификату и закрытому ключу SSL
SECURE_SSL_REDIRECT = True
SECURE_SSL_HOST = '80.72.180.130'  # Замените на ваш домен
SECURE_SSL_PROXY = True

# ...

# Только для разработки можно использовать самоподписанный сертификат
# Убедитесь, что вы заменили пути на правильные расположения файлов
SSL_CERTIFICATE_KEY = '/mnt/ks/Works/site/Converter/two_level_morphanalyzer/django3.key'
SSL_CERTIFICATE = '/etc/ssl/certs/django3.crt'

# ...


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#'127.0.0.1'
ALLOWED_HOSTS = [ '80.72.180.130']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analyzer.apps.AnalyzerConfig',
    'ckeditor',
    'rest_framework',
    'django_extensions',
    "debug_toolbar",
    'sslserver',
    'captcha',
]
#WSGIDaemonProcess my_django_app python-home=/home/user/anaconda3/envs/site python-path=/mnt/ks/Works/site/Converter/two_level_morphanalyze
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]
RECAPTCHA_PUBLIC_KEY = '6LfYy4koAAAAABqNb5WjFTj68wkPxAkCpRmE85WC'
RECAPTCHA_PRIVATE_KEY = '6LfYy4koAAAAALfeWuJmhwL6AUIVMKlW9C0Vpr6v'

ROOT_URLCONF = 'two_level_morphanalyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'two_level_morphanalyzer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/audios/')
MEDIA_URL = '/media/audios/'

INTERNAL_IPS = [
    "127.0.0.1", '80.72.180.130'
]
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'audios_cache'),
    }
}
